config/routes.rb
Tally::Application.routes.draw do
  resources :payments
  resources :clients
  resources :invoices do
    resources :expenses
    get :preview, on: :member
  end
  devise_for :users
  root 'pages#index'
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  title      :string(255)
#  client_id  :integer
#

# == An invoice that will be sent to a client
class Invoice < ActiveRecord::Base
  has_many :expenses
  has_one :payment
  belongs_to :client
  validates_presence_of :client
  scope :all_for_user, -> (user_id) { Invoice.joins(:client).load.merge Client.all_for_user(user_id) }
  def total
    expenses.map(&:total).inject(0.0) { |a, b| a + b }
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  layout "invoice", only: :preview
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :preview

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all_for_user(current_user)
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  def preview
    @invoice = Invoice.find params[:id]
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    respond_to do |format|
      # TODO: Make this less ugly
      if ((can_access_client invoice_params, @invoice) && @invoice.save)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      # I'm not getting the invoice directly from here because ActiveRecord
      # makes joined models read only
      user_invoices = Invoice.all_for_user(current_user).pluck(:id)
      @invoice = Invoice.find(params[:id])
      unless user_invoices.include? @invoice.id
        flash[:notice] = "Could not find requested invoice"
        redirect_to invoices_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params[:invoice].permit(:title, :client_id)
    end

    # TODO: Refactor into respective models
    def can_access_client invoice_params, invoice
      (current_user.clients.pluck(:id).include?(invoice_params["client_id"].to_i) ||
      current_user.clients.pluck(:id).include?(invoice.client.try(:id)))
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.haml
= simple_form_for @invoice do |f|
  = f.input :title
  = f.association :client, include_blank: false
  = f.submit 'Save'

app/views/invoices/edit.html.haml
%h2 Edit Invoice
= render 'form'

app/views/invoices/index.html.haml
.grid-12
  %h2 Invoices
  %table
    %tr
      %th Title
      %th Total
      %th Paid?
      %th Actions
    - if @invoices.count > 0
      - @invoices.each do |invoice|
        %tr
          %td= invoice.title
          %td= number_to_currency invoice.total
          %td= invoice.payment.blank? ? "No" : "Yes"
          %td.actions
            = link_to Tally::Application::SHOW.html_safe, invoice, class: "ss-icon"
            = link_to Tally::Application::EDIT.html_safe, edit_invoice_path(invoice), class: "ss-icon"
            = link_to Tally::Application::DESTROY.html_safe, invoice, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "ss-icon", id: "destroy"
    - else
      %tr
        %td{ colspan: 10 } You currently do not have any invoices
  = link_to 'New Invoice', new_invoice_path, class: :button

app/views/invoices/new.html.haml
%h2 New Invoice
= render 'form'

app/views/invoices/preview.html.haml
.grid-12
  %h1 Invoice
  %h2= @invoice.title
  %table
    %tr
      %th Client
      %th Date Created
      %th Total
    %tr
      %td= @invoice.client.name
      %td= @invoice.created_at.strftime("%d/%m/%Y")
      %td= number_to_currency @invoice.total
  - unless @invoice.payment.blank?
    %table
      %tr
        %th Payment Status
        %th Date Paid
        %th Amount
      %tr
        %td Paid
        %td= @invoice.payment.created_at.strftime("%d/%m/%Y")
        %td= number_to_currency @invoice.total
  %h3 Line Items
  %table
    %tr
      %th Task
      %th Hours
      %th Rate
      %th Total
    - if @invoice.expenses.count > 0
      - @invoice.expenses.each do |expense|
        %tr
          %td= expense.task
          %td= expense.time
          %td= number_to_currency expense.rate
          %td= number_to_currency expense.total
    - else
      %tr
        %td{ colspan: 10 } This invoice does not have any line items
  .invoice-details
    %p All balances due are payable upon reception of invoice. Interest on past due balances is 18% per annum or 1.5% per month. Thank you for your business. We look forward to our continued working relationship during this process.
  = simple_form_for :payment, url: payments_path do |f|
    = f.input :amount, as: :hidden, input_html: { value: @invoice.total }
    = f.input :invoice_id, as: :hidden, input_html: { value: @invoice.id }
  - if signed_in?
    = link_to "Back to Invoice", invoice_path(@invoice), class: :button
  - if @invoice.payment.blank?
    = link_to "Pay Invoice", "#", class: :button, id: "pay-invoice-button"
    %script{ src: "https://checkout.stripe.com/checkout.js" }
    :coffeescript
      handler = StripeCheckout.configure(
        key: "#{Rails.configuration.stripe[:publishable_key]}"
        image: "/assets/logo@2x.png"
        token: (token, args) ->
          stripe_token_input = $('<input type=hidden name=stripe_token />').val(token)
          $('form').append(stripe_token_input).submit()
      )
      document.getElementById("pay-invoice-button").addEventListener "click", (e) ->
        handler.open
          name: "Invoice"
          description: "#{@invoice.title}"
          amount: "#{@invoice.total * 100}"
        e.preventDefault()

app/views/invoices/show.html.haml
.grid-12
  %h2= @invoice.title
  %h3 Details
  %table
    %tr
      %th Client
      %th Date Created
      %th Total
    %tr
      %td= @invoice.client.name
      %td= @invoice.created_at.strftime("%d/%m/%Y")
      %td= number_to_currency @invoice.total
  - unless @invoice.payment.blank?
    %table
      %tr
        %th Payment Status
        %th Date Paid
        %th Amount
      %tr
        %td Paid
        %td= @invoice.payment.created_at.strftime("%d/%m/%Y")
        %td= number_to_currency @invoice.total
  %h3 Line Items
  %table
    %tr
      %th Task
      %th Amount
      %th Actions
    - if @invoice.expenses.count > 0
      - @invoice.expenses.each do |expense|
        %tr
          %td= expense.task
          %td= number_to_currency expense.total
          %td.actions
            = link_to content_tag(:i, Tally::Application::SHOW.html_safe, class: "ss-icon"), invoice_expense_path(@invoice, expense)
            = link_to content_tag(:i, Tally::Application::EDIT.html_safe, class: "ss-icon"), edit_invoice_expense_path(@invoice, expense)
            = link_to content_tag(:i, Tally::Application::DESTROY.html_safe, class: "ss-icon"), invoice_expense_path(@invoice, expense), :method => :delete, :data => { :confirm => 'Are you sure?' }
    - else
      %tr
        %td{ colspan: 10 } This invoice does not have any line items
  - if @invoice.payment.blank?
    .preview{ "data-no-turbolink" => true }
      = link_to "Preview", preview_invoice_path(@invoice), class: :button
    = link_to "Add Line Item", new_invoice_expense_path(@invoice), class: :button
    = link_to "Edit #{ @invoice.title } Invoice", edit_invoice_path(@invoice), class: :button