config/routes.rb
Tally::Application.routes.draw do
  resources :payments
  resources :clients
  resources :invoices do
    resources :expenses
    get :preview, on: :member
  end
  devise_for :users
  root 'pages#index'
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  name       :string(255)
#  user_id    :integer
#

# == Represents a client that will receive invoices
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :invoices
  validates_presence_of :user
  scope :all_for_user, -> (user_id) { where(user_id: user_id) }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /clients
  # GET /clients.json
  def index
    @clients = current_user.clients
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params.merge({user_id: current_user.to_param}))

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      begin
        @client = current_user.clients.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        flash[:notice] = "Could not find requested client"
        redirect_to clients_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params[:client].permit(:name)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= simple_form_for @client do |f|
  = f.input :name
  = f.input :user, as: :hidden, input_html: { value: current_user.id }
  = f.submit 'Save'

app/views/clients/edit.html.haml
%h2 Edit Client
= render 'form'

app/views/clients/index.html.haml
.grid-12
  %h2 Clients
  %table
    %tr
      %th Title
      %th Invoices
      %th Actions
    - if @clients.count > 0
      - @clients.each do |client|
        %tr
          %td= client.name
          %td= client.invoices.count
          %td.actions
            = link_to Tally::Application::SHOW.html_safe, client, class: "ss-icon"
            = link_to Tally::Application::EDIT.html_safe, edit_client_path(client), class: "ss-icon"
            = link_to Tally::Application::DESTROY.html_safe, client, method: :delete, data: { confirm: 'Are you sure?' }, class: "ss-icon", id: "destroy"
    - else
      %tr
        %td{ colspan: 10 } You currently do not have any clients
  = link_to 'New Client', new_client_path, class: :button

app/views/clients/new.html.haml
%h2 New Client
= render 'form'

app/views/clients/show.html.haml
.grid-12
  %h2= @client.name
  %h3 Invoices
  %table
    %tr
      %th Title
      %th Total
      %th Actions
    - if @client.invoices.count > 0
      - @client.invoices.each do |invoice|
        %tr
          %td= invoice.title
          %td= number_to_currency invoice.total
          %td.actions
            = link_to Tally::Application::SHOW.html_safe, invoice, class: "ss-icon"
            = link_to Tally::Application::EDIT.html_safe, edit_invoice_path(invoice), class: "ss-icon"
            = link_to Tally::Application::DESTROY.html_safe, invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: "ss-icon"
    - else
      %tr
        %td{ colspan: 10 } This client does not have any invoices
  = link_to "Edit #{@client.name}", edit_client_path(@client), class: :button