config/routes.rb
Tally::Application.routes.draw do
  resources :payments
  resources :clients
  resources :invoices do
    resources :expenses
    get :preview, on: :member
  end
  devise_for :users
  root 'pages#index'
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :integer          not null, primary key
#  amount     :decimal(, )
#  created_at :datetime
#  updated_at :datetime
#  invoice_id :integer
#

class Payment < ActiveRecord::Base
  belongs_to :invoice

  validates :invoice, :amount, presence: true
  validates :amount, numericality: true
  
  scope :all_for_user, -> (user_id) { Payment.joins(:invoice).load.merge Invoice.all_for_user(user_id) }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all_for_user(current_user)
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    respond_to do |format|
      if ((can_access_invoice payment_params, @payment) && @payment.save)
        format.html { redirect_to preview_invoice_path(@payment.invoice), notice: 'Congratulations! Your payment was successfully processed.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { redirect_to preview_invoice_path(@payment.invoice), notice: 'We were unable to process your payment. Please try again.' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      # I'm not getting the payment directly from here because ActiveRecord
      # makes joined models read only
      user_payments = Payment.all_for_user(current_user).collect { |p| p.id }
      @payment = Payment.find(params[:id])
      unless user_payments.include? @payment.id
        flash[:notice] = "Could not find requested payment"
        redirect_to payments_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:invoice_id, :amount)
    end

    def can_access_invoice payment_params, payment
      (Invoice.pluck(:id).include?(payment_params["invoice_id"].to_i) ||
      Invoice.pluck(:id).include?(payment.invoice.try(:id)))
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
= form_for @payment do |f|
  - if @payment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@payment.errors.count, "error")} prohibited this payment from being saved:"
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :expense
    = f.text_field :expense
  .field
    = f.label :amount
    = f.text_field :amount
  .actions
    = f.submit 'Save'

app/views/payments/edit.html.haml
%h1 Editing payment

= render 'form'

= link_to content_tag(:i, Tally::Application::SHOW.html_safe, class: "ss-icon"), @payment
\|
= link_to 'Back', payments_path

app/views/payments/index.html.haml
.grid-12
  %h2 Payments
  %table
    %tr
      %th Amount
      %th Invoice
      %th Client
    - if @payments.count > 0
      - @payments.each do |payment|
        %tr
          %td= number_to_currency payment.amount
          %td= payment.invoice.title
          %td= payment.invoice.client.name
    - else
      %tr
        %td{ colspan: 10 } You currently do not have any payments

app/views/payments/new.html.haml
%h1 New payment

= render 'form'

= link_to 'Back', payments_path

app/views/payments/show.html.haml
%p#notice= notice

%p
  %b Expense:
  = @payment.expense
%p
  %b Amount:
  = @payment.amount

= link_to 'Edit', edit_payment_path(@payment)
\|
= link_to 'Back', payments_path